---
# Beware: most of our tests here are run in parallel.
# To add new tests you'll need to add a new host to the inventory and a matching
# vars file should include the aws_region and aws credentials
- name: Create ec2 key for event source eda cloudtrail tests
  hosts: all
  gather_facts: false
  tasks:
    - module_defaults:
        group/aws:
          region: "{{ aws_region }}"
          access_key: "{{ aws_access_key }}"
          secret_key: "{{ aws_secret_key }}"
          session_token: "{{ security_token | default(omit) }}"
    
      block:

        # ============================================================
        # Test: create new key by AWS (key_material not provided)
        # ============================================================
        - name: Test creating a new key pair (check_mode)
          amazon.aws.ec2_key:
            name: "{{ ec2_key_name }}"
            state: present
            tags:
              snake_case: a_snake_case_value
              CamelCase: CamelCaseValue
              spaced key: Spaced value
          register: result
          check_mode: true

        - name: Assert creating a new key pair
          ansible.builtin.assert:
            that:
              - result is changed

        - name: Assert that key pair was not created
          amazon.aws.ec2_key_info:
            names:
              - "{{ ec2_key_name }}"
          register: aws_keypair
          failed_when: aws_keypair.keypairs | length > 0

        - name: Test creating a new key pair
          amazon.aws.ec2_key:
            name: "{{ ec2_key_name }}"
            state: present
            tags:
              snake_case: a_snake_case_value
              CamelCase: CamelCaseValue
              spaced key: Spaced value
          register: result

        - name: Assert creating a new key pair
          ansible.builtin.assert:
            that:
              - result is changed
              - '"key" in result'
              - '"name" in result.key'
              - '"fingerprint" in result.key'
              - '"private_key" in result.key'
              - '"id" in result.key'
              - '"tags" in result.key'
              - result.key.name == ec2_key_name
              - result.key.id.startswith('key-')
              - '"snake_case" in result.key.tags'
              - result.key.tags['snake_case'] == 'a_snake_case_value'
              - '"CamelCase" in result.key.tags'
              - result.key.tags['CamelCase'] == 'CamelCaseValue'
              - '"spaced key" in result.key.tags'
              - result.key.tags['spaced key'] == 'Spaced value'

        - name: Assert that key pair was created
          amazon.aws.ec2_key_info:
            names:
              - "{{ ec2_key_name }}"
          register: aws_keypair
          failed_when: aws_keypair.keypairs | length == 0

        - name: Gather info about the key pair
          amazon.aws.ec2_key_info:
            names: "{{ ec2_key_name }}"
          register: key_info

        - name: Assert the gathered key info
          ansible.builtin.assert:
            that:
              - key_info.keypairs[0].key_name == ec2_key_name
              - key_info.keypairs[0].key_pair_id.startswith('key-')
              - '"snake_case" in key_info.keypairs[0].tags'
              - key_info.keypairs[0].tags['snake_case'] == 'a_snake_case_value'
              - '"CamelCase" in key_info.keypairs[0].tags'
              - key_info.keypairs[0].tags['CamelCase'] == 'CamelCaseValue'
              - '"spaced key" in key_info.keypairs[0].tags'
              - key_info.keypairs[0].tags['spaced key'] == 'Spaced value'
        
        - name: Pause to wait for events CreateKeyPair and DeleteKeyPair to be processed
          ansible.builtin.wait_for:
            timeout: 360


        # # ============================================================
        # # Test: remove the key by AWS
        # # ============================================================
        # - name: Test removing an existent key (check mode)
        #   amazon.aws.ec2_key:
        #     name: "{{ ec2_key_name }}"
        #     state: absent
        #   register: result
        #   check_mode: true

        # - name: Assert removing an existent key
        #   ansible.builtin.assert:
        #     that:
        #       - result is changed

        # - name: Assert using check_mode did not removed key pair
        #   amazon.aws.ec2_key_info:
        #     names:
        #       - "{{ ec2_key_name }}"
        #   register: keys
        #   failed_when: keys.keypairs | length == 0

        # - name: Test removing an existent key
        #   amazon.aws.ec2_key:
        #     name: "{{ ec2_key_name }}"
        #     state: absent
        #   register: result

        # - name: Assert removing an existent key
        #   ansible.builtin.assert:
        #     that:
        #       - result is changed
        #       - '"key" in result'
        #       - result.key == None

        # - name: Assert that key pair was removed
        #   amazon.aws.ec2_key_info:
        #     names:
        #       - "{{ ec2_key_name }}"
        #   register: keys
        #   failed_when: keys.keypairs | length > 0

      always:
        # ============================================================
        - name: Always delete the key we might create
          amazon.aws.ec2_key:
            name: "{{ ec2_key_name }}"
            state: absent
          ignore_errors: true
